# create environment in place
# conda|mamba env create --file environment.yml --prefix ./venv --quiet
name: default-RL

channels:
  - conda-forge
dependencies:
  - python==3.10.11
  - pip==23.0.1
  - gymnasium
  - matplotlib
  - numba
  - numpy
  - pygame
  - scipy
  - stable-baselines3==2.1.0
  - snakeviz
  - pip:
    - -r Python/requirements.txt # install from requirements.txte