# create environment in place
# conda env create --file environment.yml --prefix ./venv --quiet
name: default-RL

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10.11
  - pip==23.0.1
  - pip:
    - -r Python/requirements.txt