function u_func = backst(in1)
%BACKST
%    U_FUNC = BACKST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Jun-2023 03:39:00

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
mt1 = [conj(x1).*1.901953330310394e-6+conj(x4).*4.749836624362599e-10];
mt2 = [conj(x2).*(-1.896615766665837e-6)-conj(x5).*4.739169831748717e-10];
mt3 = [conj(x3).*(-1.893063816080669e-6)-conj(x6).*4.732068031697711e-10];
u_func = [mt1;mt2;mt3];z
